CREATE SEQUENCE SEQ_PRODUCT_IO;

CREATE TABLE PRODUCT_IO(
    IO_NUM NUMBER CONSTRAINT PK_IO_NUM PRIMARY KEY,
    PRODUCT_ID VARCHAR2(30) CONSTRAINT FK_PRODUCT_ID REFERENCES PRODUCT_STOCK(PRODUCT_ID),
    IO_DATE DATE CONSTRAINT NN_IO_DATE NOT NULL,
    AMOUNT NUMBER CONSTRAINT NN_AMOUNT NOT NULL,
    STATUS VARCHAR2(10) CHECK(STATUS IN('입고','출고'))   
);

ALTER TABLE PRODUCT

COMMIT;

CREATE OR REPLACE TRIGGER TRG_P_IO AFTER
    INSERT ON PRODUCT_IO
    FOR EACH ROW    
BEGIN
    IF :NEW.STATUS = '입고'
    THEN
        UPDATE PRODUCT_STOCK
        SET STOCK = STOCK + :NEW.AMOUNT
        WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
    END IF;
    
    IF :NEW.STATUS = '출고'
    THEN
        UPDATE PRODUCT_STOCK
        SET STOCK = STOCK - :NEW.AMOUNT
        WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
    END IF;
END;
/

DELETE PRODUCT_IO;

INSERT INTO PRODUCT_IO
    VALUES( SEQ_PRODUCT_IO.NEXTVAL,'nb_ss7','19/07/01',30,'입고');
    
INSERT INTO PRODUCT_IO
    VALUES( SEQ_PRODUCT_IO.NEXTVAL,'nb_ss7','19/07/02',3,'출고');
    
INSERT INTO PRODUCT_IO
    VALUES( SEQ_PRODUCT_IO.NEXTVAL,'pc_ibm','19/07/02',10,'입고');
    


CREATE VIEW PRODUCT
AS
SELECT 
    IO_NUM 입출고번호,
    PRODUCT_ID 상품ID,
    P_NAME 상품명,
    IO_DATE 입출고일,
    AMOUNT 입출고수량,
    STATUS 입출고상태
FROM PRODUCT_IO I
LEFT JOIN PRODUCT_STOCK S USING(PRODUCT_ID);


SELECT * FROM PRODUCT;
SELECT * FROM PRODUCT_IO;
SELECT * FROM PRODUCT_STOCK;

commit;

